// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RebootDevice(arg1:string,arg2:string):Promise<void>;

export function ScanNetwork(arg1:string):Promise<scanner.ScanResults>;
