// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['client']['App']['Greet'](arg1);
}

export function RebootDevice(arg1, arg2) {
  return window['go']['client']['App']['RebootDevice'](arg1, arg2);
}

export function ScanNetwork(arg1) {
  return window['go']['client']['App']['ScanNetwork'](arg1);
}
