// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest_Action int32

const (
	CommandRequest_UNKNOWN CommandRequest_Action = 0
	CommandRequest_REBOOT  CommandRequest_Action = 1
	CommandRequest_UPDATE  CommandRequest_Action = 2
)

// Enum value maps for CommandRequest_Action.
var (
	CommandRequest_Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "REBOOT",
		2: "UPDATE",
	}
	CommandRequest_Action_value = map[string]int32{
		"UNKNOWN": 0,
		"REBOOT":  1,
		"UPDATE":  2,
	}
)

func (x CommandRequest_Action) Enum() *CommandRequest_Action {
	p := new(CommandRequest_Action)
	*p = x
	return p
}

func (x CommandRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (CommandRequest_Action) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x CommandRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandRequest_Action.Descriptor instead.
func (CommandRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2, 0}
}

// DiscoveryPacket is sent via UDP Broadcast (decrypted payload)
type DiscoveryPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MagicHeader   string                 `protobuf:"bytes,1,opt,name=magic_header,json=magicHeader,proto3" json:"magic_header,omitempty"` // "GFMA_PROBE"
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                                // Nonce used for encryption/reply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryPacket) Reset() {
	*x = DiscoveryPacket{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryPacket) ProtoMessage() {}

func (x *DiscoveryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryPacket.ProtoReflect.Descriptor instead.
func (*DiscoveryPacket) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryPacket) GetMagicHeader() string {
	if x != nil {
		return x.MagicHeader
	}
	return ""
}

func (x *DiscoveryPacket) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// DeviceInfo is the response from the Agent (encrypted)
type DeviceInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Hostname              string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress             string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress            string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	OsDistro              string                 `protobuf:"bytes,4,opt,name=os_distro,json=osDistro,proto3" json:"os_distro,omitempty"`
	KernelVersion         string                 `protobuf:"bytes,5,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	AgentVersion          string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	RemoteCommandsEnabled bool                   `protobuf:"varint,7,opt,name=remote_commands_enabled,json=remoteCommandsEnabled,proto3" json:"remote_commands_enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DeviceInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DeviceInfo) GetOsDistro() string {
	if x != nil {
		return x.OsDistro
	}
	return ""
}

func (x *DeviceInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *DeviceInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *DeviceInfo) GetRemoteCommandsEnabled() bool {
	if x != nil {
		return x.RemoteCommandsEnabled
	}
	return false
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        CommandRequest_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=protocol.CommandRequest_Action" json:"action,omitempty"`
	Args          string                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetAction() CommandRequest_Action {
	if x != nil {
		return x.Action
	}
	return CommandRequest_UNKNOWN
}

func (x *CommandRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "pong"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\bprotocol\"J\n" +
	"\x0fDiscoveryPacket\x12!\n" +
	"\fmagic_header\x18\x01 \x01(\tR\vmagicHeader\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"\x89\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1b\n" +
	"\tos_distro\x18\x04 \x01(\tR\bosDistro\x12%\n" +
	"\x0ekernel_version\x18\x05 \x01(\tR\rkernelVersion\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x126\n" +
	"\x17remote_commands_enabled\x18\a \x01(\bR\x15remoteCommandsEnabled\"\x8c\x01\n" +
	"\x0eCommandRequest\x127\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1f.protocol.CommandRequest.ActionR\x06action\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\"-\n" +
	"\x06Action\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06REBOOT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8e\x01\n" +
	"\x0eCommandService\x12E\n" +
	"\x0eExecuteCommand\x12\x18.protocol.CommandRequest\x1a\x19.protocol.CommandResponse\x125\n" +
	"\x04Ping\x12\x15.protocol.PingRequest\x1a\x16.protocol.PingResponseB0Z.github.com/apavanello/goFindMyArm/pkg/protocolb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_service_proto_goTypes = []any{
	(CommandRequest_Action)(0), // 0: protocol.CommandRequest.Action
	(*DiscoveryPacket)(nil),    // 1: protocol.DiscoveryPacket
	(*DeviceInfo)(nil),         // 2: protocol.DeviceInfo
	(*CommandRequest)(nil),     // 3: protocol.CommandRequest
	(*CommandResponse)(nil),    // 4: protocol.CommandResponse
	(*PingRequest)(nil),        // 5: protocol.PingRequest
	(*PingResponse)(nil),       // 6: protocol.PingResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0, // 0: protocol.CommandRequest.action:type_name -> protocol.CommandRequest.Action
	3, // 1: protocol.CommandService.ExecuteCommand:input_type -> protocol.CommandRequest
	5, // 2: protocol.CommandService.Ping:input_type -> protocol.PingRequest
	4, // 3: protocol.CommandService.ExecuteCommand:output_type -> protocol.CommandResponse
	6, // 4: protocol.CommandService.Ping:output_type -> protocol.PingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
